### ISSUE TITLE
Interations tests fail with segmentation fault

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/pytket-quantinuum#166]
See https://github.com/CQCL/pytket-quantinuum/actions/runs/5333733537/jobs/9684418924

**Comment by cqc-alec** [comment]
@cqc-melf Is this still an issue? (The linked logs are no longer available.)

**Comment by cqc-melf** [comment]
I have not seen it again since, not sure. I would suggest we close this and reopen it if this issues shows up again?
