### ISSUE TITLE
enable wasm in qir tests after remote update

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/pytket-quantinuum#232]
we have changed the wasm interface in qir, the tests needs to be enabled again after this is update on the remote side

**Comment by cqc-alec** [comment]
```
FAILED integration/backend_test.py::test_wasm[Language.QIR-H1-1SC] - pytket.extensions.quantinuum.backends.quantinuum.GetResultFailed: Cannot retrieve result; job status is Circui...
```

Full error:

```
"1000: Compile error: 3 Encountered Unexpected Instruction   %2 = call i64 @add_one(i64 %1)"
```

**Comment by cqc-melf** [comment]
Still not working, fails on production with:
`"1000: Compile error:  Invalid creg index for creg [\\"hyb_res0\\"]: 32"`

running wasm on production still shows the error as above

**Comment by cqc-melf** [comment]
completed via #396
