### ISSUE TITLE
Test failure: `test_simulator[Language.QIR-H1-1E]`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-quantinuum#236]
Error message is:

```
"1000: Compile error: 1 Encountered Unexpected Instruction   %0 = call i1* @create_creg(i64 2)"
```

**Comment by cqc-alec** [comment]
This is with pytket 1.20.0rc3, pytket-qir 0.2.1rc1.

**Comment by cqc-melf** [comment]
Still showing up with pytket-qir 0.3.0.

**Comment by cqc-alec** [comment]
QIR tests have been commented out: please search for `#236` and uncomment to ensure they pass (or open separate issues) before closing this one.
