### ISSUE TITLE
`check-examples` workflow does not fail when notebook checks fail

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-quantinuum#249]
See for example: https://github.com/CQCL/pytket-quantinuum/actions/runs/6438882602/job/17485916107

Looks like at least three of the notebooks are failing, but the workflow does not fail, so we don't notice.

**Comment by cqc-melf** [comment]
Solved in https://github.com/CQCL/pytket-quantinuum/pull/268
