### ISSUE TITLE
QIR submissions with more than N shots never return results (or error)

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-quantinuum#279]
For the circuit below, it looks like N=3632; I don't know if the limit depends on the circuit.

```python
from pytket.circuit import Circuit
from pytket.extensions.quantinuum import QuantinuumBackend, QuantinuumAPI, Language
from time import time
import warnings

warnings.filterwarnings("ignore")

api_handler = QuantinuumAPI(api_url="https://hqapi.quantinuum.com/")
b = QuantinuumBackend("H1-1E", api_handler=api_handler)

c = Circuit(2).H(0).CX(0, 1).measure_all()
c1 = b.get_compiled_circuit(c)

for n_shots in [3632, 3633]:
    t0 = time()
    r = b.run_circuit(c1, n_shots=n_shots, language=Language.QIR)
    t1 = time()
    print(n_shots, t1 - t0)
```

Output:

```
3632 7.960129261016846
^C
```

No problems with QASM submission.

**Comment by cqc-alec** [comment]
It seems that the job is actually run, and shows on the UI. It is also possible to retrieve the results with pytket-quantinuum by setting `use_websocket=False` in `get_result()`. But when using websockets (the default), we get no response.

**Comment by mramirez2021** [comment]
@cqc-alec any chance you have the job id(s) from this testing?

**Comment by cqc-alec** [comment]
> @cqc-alec any chance you have the job id(s) from this testing?

Sure. From a run just now (QA env), using websockets:

3632 shots: successful, job ID `f621f33ceeae4779a03f569b7eb478b4`
3633 shots: unsuccessful (no reply on websocket), job ID `a500119299084e10b74ed3b7689f50cd`

**Comment by cqc-alec** [comment]
Retested. This issue seems to be fixed.
