### ISSUE TITLE
`AttributeError: 'QirGenerator' object has no attribute 'wasm'`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-quantinuum#509]
When running the CI tests after switching the default submission language to QIR:

```
FAILED integration/backend_test.py::test_wasm_costs[H1-1E] - AttributeError: 'QirGenerator' object has no attribute 'wasm'
```

See #508 .

**Comment by cqc-melf** [comment]
Do we want to add an language option to the cost function? Or is that always using the default?

**Comment by cqc-alec** [comment]
> Do we want to add an language option to the cost function? Or is that always using the default?

We should probably add the option to the `cost()` function, with the same default as `process_circuits()`. I'd expect the costs to be the same but you never know...
