### ISSUE TITLE
Incorrect shots length after submitting QIR

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket-quantinuum#510]
When running the CI tests after switching the default submission language to QIR:

```
FAILED integration/backend_test.py::test_scratch_removal[H1-1SC] - assert False
 +  where False = all(<generator object test_scratch_removal.<locals>.<genexpr> at 0x7f7fec9bb5a0>)
```

See #508 .

**Comment by cqc-melf** [comment]
I don't see a reason why this should only be tested with the default language, any objections on updating this?

**Comment by cqc-melf** [comment]
The circuit has the following bits:
```[cb0[0], cb0[1], cb1[0], cb1[1], cb1[2], tk_SCRATCH_BIT[0], tk_SCRATCH_BIT[1], tk_SCRATCH_BIT[2]]```
We get all 8 of them back, I would assume that we want to exclude the `tk_SCRATCH_BIT` at some point. Do we want to do this when generating the qir or later when we get the results?

**Comment by cqc-melf** [comment]
So I think we are missing the part here which is only done for qasm:
```
                    used_scratch_regs = _used_scratch_registers(quantinuum_circ)
                    for name, count in Counter(
                        bit.reg_name
                        for bit in c0.bits
                        if not _is_scratch(bit) or bit.reg_name in used_scratch_regs
                    ).items():
                        for i in range(count):
                            results_selection.append((name, i))

```

I will make a PR to add this
