### ISSUE TITLE
MacOS Intel-chip pytket wheel does not exist

### ISSUE THREAD

**Issue by vprusso** [CQCL/pytket-quantinuum#544]
I am attempting to install `pytket` and am encountering the following error:

```
  - Installing pytket (1.34.0): Failed

  RuntimeError

  Unable to find installation candidates for pytket (1.34.0)

  at ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install pytket.
```

#### System information:

```
MacOS Monterey 
Version: 12.7.6
2.3 GHz 8-Core Intel Core i9
```

#### Python information:

```
Python 3.12.6
```

This fails as there is no existing wheel for the Intel-based chipset for MacOS

Likely, it seems that the necessary wheel just needs to be generated for Python 3.12 for this chipset (which is not present here):
https://pypi.org/project/pytket/#files

Could a new release with the appropriate wheel file be pushed? Feel free to let me know if any additional information on my side would be helpful.

**Comment by cqc-alec** [comment]
Hi,

Thanks for the report. Are you able to upgrade your MacOS to 13 or higher? We have stopped supporting MacOS 12 since github actions deprecated their `macos-12` runners meaning we had no easy way to test them.

**Comment by vprusso** [comment]
Hi @cqc-alec 

Thank you, that was indeed the issue. I updated my OS and it works! Thank you! I'll close out this issue.
