### ISSUE TITLE
ZZMax mapping when converting to qiskit

### ISSUE THREAD

**Issue by oneTimePad** [CQCL/pytket-quantinuum#68]
It appears that there is no mapping for the ZZMax gate to qiskit's Rzz(pi/2) in tk_to_qiskit. Thus, when converting circuits that were transpiled for the Quantinuum device back to qiskit, tk_to_qiskit throws an exception.

**Comment by cqc-melf** [comment]
Thank you for reporting. We will take a look! We hope to fix this in the next release.
